# Generated by Django 6.0.1 on 2026-01-29 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=50, verbose_name="ยี่ห้อ")),
                ("model_name", models.CharField(max_length=100, verbose_name="รุ่น")),
                ("year", models.CharField(max_length=4, verbose_name="ปี (ค.ศ.)")),
                ("price", models.IntegerField(verbose_name="ราคา (บาท)")),
                (
                    "gear",
                    models.CharField(
                        choices=[("AUTO", "ออโต้"), ("MANUAL", "ธรรมดา")],
                        default="AUTO",
                        max_length=10,
                        verbose_name="เกียร์",
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=50, verbose_name="สี"),
                ),
                (
                    "mileage",
                    models.CharField(
                        blank=True,
                        help_text="เช่น 45,xxx",
                        max_length=50,
                        verbose_name="เลขไมล์",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="เช่น รถมือเดียว น็อตไม่ขยับ",
                        verbose_name="รายละเอียดรถ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "✅ ว่าง (พร้อมขาย)"),
                            ("RESERVED", "🟡 ติดจอง"),
                            ("SOLD", "🔴 ขายแล้ว"),
                        ],
                        default="AVAILABLE",
                        max_length=10,
                        verbose_name="สถานะ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "รถยนต์",
                "verbose_name_plural": "ข้อมูลรถยนต์ทั้งหมด",
            },
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="cars/%Y/%m/", verbose_name="รูปภาพ"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="showroom.car",
                    ),
                ),
            ],
        ),
    ]
