# Generated by Django 6.0.1 on 2026-01-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="installment",
            field=models.IntegerField(
                blank=True,
                help_text="ใส่แค่ตัวเลข ถ้าไม่ใส่ ระบบจะไม่แสดง",
                null=True,
                verbose_name="ผ่อนเริ่มต้น (บาท/เดือน)",
            ),
        ),
    ]
