# Generated by Django 6.0.1 on 2026-01-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0002_car_installment"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("DIESEL", "ดีเซล"),
                    ("PETROL", "เบนซิน"),
                    ("HYBRID", "ไฮบริด"),
                    ("EV", "ไฟฟ้า 100%"),
                ],
                default="DIESEL",
                max_length=10,
                verbose_name="เชื้อเพลิง",
            ),
        ),
    ]
