# Generated by Django 6.0.1 on 2026-02-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0003_car_fuel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="down_payment",
            field=models.IntegerField(
                default=0,
                help_text="ใส่ 0 จะแสดงเป็น 'ฟรีดาวน์'",
                verbose_name="เงินดาวน์ (บาท)",
            ),
        ),
    ]
