# Generated by Django 5.2.1 on 2026-02-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0004_car_down_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="down_payment",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="ใส่ 0 = ฟรีดาวน์, เว้นว่าง = โชว์ขีด (-)",
                null=True,
                verbose_name="เงินดาวน์ (บาท)",
            ),
        ),
    ]
