# Generated by Django 6.0.1 on 2026-03-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0006_alter_car_down_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="ยอดเข้าชม"),
        ),
        migrations.AlterField(
            model_name="car",
            name="down_payment",
            field=models.CharField(
                blank=True,
                default=0,
                help_text="ใส่ 0 = ฟรีดาวน์, ใส่เป็นข้อความก็ได้เช่น 2x,xxx",
                max_length=50,
                null=True,
                verbose_name="เงินดาวน์ (บาท)",
            ),
        ),
    ]
