# Generated by Django 5.2.1 on 2026-03-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0007_car_views_count_alter_car_down_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="installment",
            field=models.CharField(
                blank=True,
                help_text="ใส่เป็นตัวเลขหรือข้อความก็ได้ เช่น 3,xxx",
                max_length=50,
                null=True,
                verbose_name="ผ่อนเริ่มต้น (บาท/เดือน)",
            ),
        ),
    ]
